baseURL = "https://olka.github.io/personal-blog/"
publishDir = "docs"

[params]
    sidebartitle = "Alex Kachur's"
    sidebartagline = "Tech Blog"
    sidebarphoto = "https://raw.githubusercontent.com/olka/personal-blog/master/static/img/photo.jpg"
    languageCode = "en-us"

[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/alexkachur"
    identifier = "linkedin"    

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/olka"
    identifier = "github"

nocomment = false
notoc = false
totop = true
banner = "none"
bannerfill = true
bannerinline = true